import { Ban, ExternalLink, Gift, Plus, RotateCcw, X } from "lucide-react";
import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../api";
import { useToast } from "../components/Toast";
import { EmptyState, ErrorState, formatDate, LoadingState, PageHeader, Pagination, RefreshButton, SearchBox, StatusBadge } from "../components/Ui";
import { useResource } from "../hooks/useResource";
import type { Chat, Giveaway, PageResult } from "../types";

export function GiveawaysPage() {
  const [params, setParams] = useSearchParams(); const page = Number(params.get("page") ?? 1); const search = params.get("search") ?? ""; const status = params.get("status") ?? "";
  const state = useResource<PageResult<Giveaway>>(`/api/admin/giveaways?page=${page}&pageSize=20&search=${encodeURIComponent(search)}&status=${status}`);
  const [creating, setCreating] = useState(false);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); setParams(next, { replace: true }); };
  return <>
    <PageHeader title="抽奖活动" description="活动状态、参与人数与开奖任务" actions={<><button className="button primary" onClick={() => setCreating(true)}><Plus size={16} />新建抽奖</button><RefreshButton onClick={state.reload} spinning={state.refreshing} /></>} />
    <section className="panel table-panel"><div className="filter-bar"><SearchBox value={search} onChange={(value) => setFilter("search", value)} placeholder="标题、奖品或群组" /><select value={status} onChange={(event) => setFilter("status", event.target.value)}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="ACTIVE">进行中</option><option value="DRAWN">已开奖</option><option value="FAILED">失败</option><option value="CANCELLED">已取消</option></select></div>
      {state.loading ? <LoadingState /> : state.error || !state.data ? <ErrorState message={state.error ?? "暂无数据"} retry={state.reload} /> : state.data.items.length === 0 ? <EmptyState title="暂无抽奖活动" /> : <><div className="table-scroll"><table><thead><tr><th>活动</th><th>群组</th><th>开奖时间</th><th>参与人数</th><th>奖品</th><th>状态</th><th>操作</th></tr></thead><tbody>{state.data.items.map((item) => <GiveawayRow item={item} onChanged={state.reload} key={item.id} />)}</tbody></table></div><Pagination page={state.data.page} pageSize={state.data.pageSize} total={state.data.total} onPage={(value) => setFilter("page", String(value))} /></>}
    </section>
    {creating && <CreateGiveawayDialog close={() => setCreating(false)} onSaved={() => { setCreating(false); state.reload(); }} />}
  </>;
}

function CreateGiveawayDialog({ close, onSaved }: { close: () => void; onSaved: () => void }) {
  const toast = useToast(); const chats = useResource<PageResult<Chat>>("/api/admin/chats?page=1&pageSize=100&status=ACTIVE"); const [chatId, setChatId] = useState(""); const [title, setTitle] = useState(""); const [prize, setPrize] = useState(""); const [keyword, setKeyword] = useState(""); const [winnersCount, setWinnersCount] = useState("1"); const [drawAt, setDrawAt] = useState(""); const [working, setWorking] = useState(false);
  const submit = async () => { const date = new Date(drawAt); if (!chatId || !title.trim() || !prize.trim() || !keyword.trim() || !drawAt || Number.isNaN(date.getTime())) { toast.notify("请完整填写抽奖信息", "error"); return; } setWorking(true); try { await api("/api/admin/giveaways", { method: "POST", body: JSON.stringify({ chatId, title: title.trim(), prize: prize.trim(), keyword: keyword.trim(), winnersCount: Number(winnersCount), drawAt: date.toISOString() }) }); toast.notify("抽奖已创建并安排开奖"); onSaved(); } catch (caught) { toast.notify(caught instanceof Error ? caught.message : "创建失败", "error"); } finally { setWorking(false); } };
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="modal"><div className="modal-header"><div><h2>新建关键词抽奖</h2><p>用户发送指定关键词参与，系统按时开奖</p></div><button className="icon-button" title="关闭" onClick={close}><X size={18} /></button></div><div className="form-stack"><label><span>群组</span><select value={chatId} onChange={(event) => setChatId(event.target.value)}><option value="">选择群组</option>{chats.data?.items.map((chat) => <option key={chat.id} value={chat.id}>{chat.title ?? chat.telegramChatId}</option>)}</select></label><label><span>活动标题</span><input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label><span>奖品</span><input value={prize} onChange={(event) => setPrize(event.target.value)} /></label><label><span>参与关键词</span><input value={keyword} onChange={(event) => setKeyword(event.target.value)} /></label><label><span>中奖人数</span><input type="number" min="1" max="100" value={winnersCount} onChange={(event) => setWinnersCount(event.target.value)} /></label><label><span>开奖时间</span><input type="datetime-local" value={drawAt} onChange={(event) => setDrawAt(event.target.value)} /></label></div><div className="modal-actions"><button className="button secondary" onClick={close}>取消</button><button className="button primary" disabled={working} onClick={submit}><Gift size={16} />创建抽奖</button></div></section></div>;
}

function GiveawayRow({ item, onChanged }: { item: Giveaway; onChanged: () => void }) {
  const toast = useToast(); const [working, setWorking] = useState(false);
  const cancel = async () => { if (!window.confirm("确认取消这个抽奖活动？")) return; setWorking(true); try { await api(`/api/admin/giveaways/${item.id}/cancel`, { method: "POST" }); toast.notify("抽奖活动已取消"); onChanged(); } catch (caught) { toast.notify(caught instanceof Error ? caught.message : "操作失败", "error"); } finally { setWorking(false); } };
  const retry = async () => { if (!window.confirm("确认重新执行这个抽奖任务？")) return; setWorking(true); try { await api(`/api/admin/giveaways/${item.id}/retry`, { method: "POST" }); toast.notify("抽奖任务已重新入队"); onChanged(); } catch (caught) { toast.notify(caught instanceof Error ? caught.message : "重试失败", "error"); } finally { setWorking(false); } };
  return <tr><td><div className="primary-cell"><span className="entity-avatar giveaway-avatar"><Gift size={16} /></span><div><strong>{item.title}</strong><small>创建者：{item.creator.username ? `@${item.creator.username}` : item.creator.firstName ?? "未知"}</small>{item.lastError && <small className="task-error" title={item.lastError}>{item.lastError}</small>}</div></div></td><td><Link className="table-link" to={`/chats/${item.chat.id}`}>{item.chat.title ?? "未命名群组"}</Link></td><td>{formatDate(item.drawAt)}</td><td>{item._count.entries} / {item.winnersCount} 位中奖名额</td><td>{item.prize}</td><td><StatusBadge value={item.status} />{item.attemptCount > 0 && <small className="table-subline">已尝试 {item.attemptCount} 次</small>}</td><td><div className="row-actions">{item.status === "FAILED" && <button className="icon-button small" disabled={working} onClick={retry} title="重新执行"><RotateCcw size={16} /></button>}{["DRAFT", "ACTIVE", "FAILED"].includes(item.status) && <button className="icon-button danger-button small" disabled={working} onClick={cancel} title="取消抽奖"><Ban size={16} /></button>}<Link className="icon-button small" to={`/chats/${item.chat.id}`} title="查看群组"><ExternalLink size={15} /></Link></div></td></tr>;
}
