import { CreditCard, Crown, Plus, ReceiptText, RefreshCw, RotateCcw } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { api } from "../api";
import { useToast } from "../components/Toast";
import { EmptyState, ErrorState, formatDate, LoadingState, PageHeader, Pagination, RefreshButton, SearchBox, StatusBadge } from "../components/Ui";
import { useResource } from "../hooks/useResource";
import type { BotSubscription, PageResult, PaymentOrder } from "../types";

type Tab = "subscriptions" | "orders";
export function MembershipsPage() {
  const [params, setParams] = useSearchParams(); const tab = (params.get("tab") as Tab | null) ?? "subscriptions";
  const setTab = (value: Tab) => setParams(value === "subscriptions" ? {} : { tab: value }, { replace: true });
  return <><PageHeader title="会员与支付" description="查看会员有效期、支付订单和人工授权记录" /><nav className="page-tabs"><button className={tab === "subscriptions" ? "active" : ""} onClick={() => setTab("subscriptions")}><Crown size={15} />会员状态</button><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><CreditCard size={15} />支付订单</button></nav>{tab === "subscriptions" ? <SubscriptionsView /> : <PaymentOrdersView />}</>;
}

function SubscriptionsView() {
  const [params, setParams] = useSearchParams(); const page = Number(params.get("page") ?? 1); const search = params.get("search") ?? ""; const status = params.get("status") ?? "";
  const state = useResource<PageResult<BotSubscription>>(`/api/admin/subscriptions?page=${page}&pageSize=20&search=${encodeURIComponent(search)}&subscriptionStatus=${status}`); const toast = useToast();
  const setFilter = (key: string, value: string) => updateFilter(params, setParams, key, value);
  const grant = async (userId: string) => { const value = window.prompt("授权月数（1-120）", "1"); const months = Number(value); if (!Number.isInteger(months) || months < 1) return; try { await api(`/api/admin/subscriptions/${userId}/grant`, { method: "POST", body: JSON.stringify({ months }) }); toast.notify("会员已授权"); state.reload(); } catch (caught) { toast.notify(errorMessage(caught, "授权失败"), "error"); } };
  const cancel = async (userId: string) => { if (!window.confirm("确认取消该用户当前会员？")) return; try { await api(`/api/admin/subscriptions/${userId}/cancel`, { method: "POST" }); toast.notify("会员已取消"); state.reload(); } catch (caught) { toast.notify(errorMessage(caught, "取消失败"), "error"); } };
  return <><div className="view-actions"><RefreshButton onClick={state.reload} spinning={state.refreshing} /></div><section className="panel table-panel"><div className="filter-bar"><SearchBox value={search} onChange={(value) => setFilter("search", value)} placeholder="用户名、姓名或 Telegram ID" /><select value={status} onChange={(event) => setFilter("status", event.target.value)}><option value="">全部状态</option><option value="ACTIVE">有效</option><option value="EXPIRED">已过期</option><option value="CANCELLED">已取消</option></select></div>{state.loading ? <LoadingState /> : state.error || !state.data ? <ErrorState message={state.error ?? "暂无数据"} retry={state.reload} /> : state.data.items.length === 0 ? <EmptyState title="暂无会员记录" /> : <><div className="table-scroll"><table><thead><tr><th>用户</th><th>状态</th><th>到期时间</th><th>来源</th><th /></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id}><td><strong>{userName(item.user)}</strong><small className="table-subline">{item.user.telegramUserId}</small></td><td><StatusBadge value={item.status} /></td><td>{formatDate(item.expiresAt)}</td><td>{item.source}</td><td><div className="row-actions"><button className="icon-button small" title="顺延会员" onClick={() => grant(item.userId)}><Plus size={15} /></button>{item.status === "ACTIVE" && <button className="icon-button small danger-button" title="取消会员" onClick={() => cancel(item.userId)}><RotateCcw size={15} /></button>}</div></td></tr>)}</tbody></table></div><Pagination page={state.data.page} pageSize={state.data.pageSize} total={state.data.total} onPage={(value) => setFilter("page", String(value))} /></>}</section></>;
}

function PaymentOrdersView() {
  const [params, setParams] = useSearchParams(); const page = Number(params.get("page") ?? 1); const search = params.get("search") ?? ""; const status = params.get("status") ?? "";
  const state = useResource<PageResult<PaymentOrder>>(`/api/admin/payment-orders?page=${page}&pageSize=20&search=${encodeURIComponent(search)}&orderStatus=${status}`); const setFilter = (key: string, value: string) => updateFilter(params, setParams, key, value); const toast = useToast();
  const run = async (item: PaymentOrder, action: "reconcile" | "retry") => { try { await api(`/api/admin/payment-orders/${item.id}/${action}`, { method: "POST" }); toast.notify(action === "reconcile" ? "订单对账完成" : "支付单已重新创建"); state.reload(); } catch (caught) { toast.notify(errorMessage(caught, "订单操作失败"), "error"); } };
  const refund = async (item: PaymentOrder) => { const note = window.prompt("请输入外部退款凭证或说明。此操作只记录退款状态，不会自动取消会员。", "已在支付商后台完成退款"); if (!note?.trim()) return; if (!window.confirm("确认已在支付商完成退款，并将该订单标记为已退款？")) return; try { await api(`/api/admin/payment-orders/${item.id}/refund`, { method: "POST", body: JSON.stringify({ note: note.trim() }) }); toast.notify("退款状态已记录"); state.reload(); } catch (caught) { toast.notify(errorMessage(caught, "记录退款失败"), "error"); } };
  return <section className="panel table-panel"><div className="filter-bar"><SearchBox value={search} onChange={(value) => setFilter("search", value)} placeholder="订单号、支付单号或用户" /><select value={status} onChange={(event) => setFilter("status", event.target.value)}><option value="">全部状态</option><option value="PENDING">待创建支付单</option><option value="WAITING">等待支付</option><option value="CONFIRMED">确认中</option><option value="FINISHED">已完成</option><option value="FAILED">失败</option><option value="EXPIRED">已过期</option><option value="REFUNDED">已退款</option></select></div>{state.loading ? <LoadingState /> : state.error || !state.data ? <ErrorState message={state.error ?? "暂无数据"} retry={state.reload} /> : state.data.items.length === 0 ? <EmptyState title="暂无支付订单" /> : <><div className="table-scroll"><table><thead><tr><th>订单</th><th>用户</th><th>套餐</th><th>金额</th><th>状态</th><th>创建时间</th><th>支付时间</th><th /></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id}><td><code>{item.id}</code><small className="table-subline">{item.providerPaymentId ?? "未生成支付单"}</small></td><td>{userName(item.user)}</td><td>{item.planKey} · {item.months}个月</td><td>{item.amountUsd} USD</td><td><StatusBadge value={item.status} /></td><td>{formatDate(item.createdAt)}</td><td>{item.paidAt ? formatDate(item.paidAt) : "-"}</td><td><div className="row-actions">{item.providerPaymentId && item.status !== "REFUNDED" && <button className="icon-button small" title="向支付商对账" onClick={() => run(item, "reconcile")}><RefreshCw size={15} /></button>}{!item.providerPaymentId && ["PENDING", "FAILED"].includes(item.status) && <button className="icon-button small" title="重试创建支付单" onClick={() => run(item, "retry")}><RotateCcw size={15} /></button>}{["CONFIRMED", "FINISHED"].includes(item.status) && <button className="icon-button small danger-button" title="记录外部退款" onClick={() => refund(item)}><ReceiptText size={15} /></button>}</div></td></tr>)}</tbody></table></div><Pagination page={state.data.page} pageSize={state.data.pageSize} total={state.data.total} onPage={(value) => setFilter("page", String(value))} /></>}</section>;
}

function updateFilter(params: URLSearchParams, setParams: ReturnType<typeof useSearchParams>[1], key: string, value: string) { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); setParams(next, { replace: true }); }
function userName(user: { username: string | null; firstName: string | null; telegramUserId: string }) { return user.username ? `@${user.username}` : user.firstName ?? user.telegramUserId; }
function errorMessage(error: unknown, fallback: string) { return error instanceof Error ? error.message : fallback; }
