import { ShieldAlert } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { EmptyState, ErrorState, formatDate, LoadingState, PageHeader, Pagination, RefreshButton, SearchBox, StatusBadge } from "../components/Ui";
import { useResource } from "../hooks/useResource";
import type { ModerationEvent, PageResult } from "../types";

export function ModerationPage() {
  const [params, setParams] = useSearchParams(); const page = Number(params.get("page") ?? 1); const search = params.get("search") ?? ""; const action = params.get("action") ?? ""; const eventType = params.get("eventType") ?? "";
  const state = useResource<PageResult<ModerationEvent>>(`/api/admin/moderation-events?page=${page}&pageSize=20&search=${encodeURIComponent(search)}&moderationAction=${action}&eventType=${eventType}`);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); setParams(next, { replace: true }); };
  return <><PageHeader title="风控事件" description="追踪内容审核、入群验证与自动处罚结果" actions={<RefreshButton onClick={state.reload} spinning={state.refreshing} />} /><section className="panel table-panel"><div className="filter-bar"><SearchBox value={search} onChange={(value) => setFilter("search", value)} placeholder="群组、用户 ID、原因或命中内容" /><select value={eventType} onChange={(event) => setFilter("eventType", event.target.value)}><option value="">全部事件</option><option value="banned_word">违禁词</option><option value="anti_spam">反垃圾</option><option value="speech_check">发言检查</option><option value="join_verification">进群验证</option><option value="blocklist">入群风控</option></select><select value={action} onChange={(event) => setFilter("action", event.target.value)}><option value="">全部处罚</option><option value="delete_only">仅删除</option><option value="warn">警告</option><option value="retry">要求重试</option><option value="decline_join_request">拒绝入群</option><option value="mute">禁言</option><option value="kick">踢出</option><option value="ban">封禁</option></select></div>{state.loading ? <LoadingState /> : state.error || !state.data ? <ErrorState message={state.error ?? "暂无数据"} retry={state.reload} /> : state.data.items.length === 0 ? <EmptyState title="暂无风控事件" /> : <><div className="table-scroll"><table><thead><tr><th>事件</th><th>群组</th><th>用户</th><th>命中内容</th><th>处罚</th><th>原因</th><th>时间</th></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id}><td><span className="inline-icon"><ShieldAlert size={15} />{eventLabel(item.eventType)}</span></td><td><Link className="table-link" to={`/chats/${item.chat.id}`}>{item.chat.title ?? "未命名群组"}</Link></td><td><code>{item.telegramUserId ?? "-"}</code></td><td>{item.matchedPattern ? <code>{item.matchedPattern}</code> : "-"}</td><td><StatusBadge value={item.action} /></td><td>{item.reason ?? "-"}</td><td>{formatDate(item.createdAt)}</td></tr>)}</tbody></table></div><Pagination page={state.data.page} pageSize={state.data.pageSize} total={state.data.total} onPage={(value) => setFilter("page", String(value))} /></>}</section></>;
}
function eventLabel(value: string) { return ({ banned_word: "违禁词", anti_spam: "反垃圾", speech_check: "发言检查", join_verification: "进群验证", blocklist: "入群风控" } as Record<string, string>)[value] ?? value; }
